const PREFIX=process.env.PREFIX||".";
const OWN=(process.env.OWNER_NUMBERS||"").split(",").map(x=>x.trim()).filter(Boolean);
const E=["❤️", "🩷", "🧡", "💛", "💚", "🩵", "💙", "💜", "🤎", "🖤", "🩶", "🤍", "💖", "💗", "💓", "💞", "💕", "💘", "💝", "💟", "❣️", "💌", "❤️‍🔥", "❤️‍🩹", "😍", "🥰", "😘", "😻", "🤩", "😊", "☺️", "😇", "🥹", "😂", "🤣", "😄", "😁", "😆", "😅", "🙂", "🙃", "😉", "😌", "🤗", "🤭", "😎", "🥳", "🤠", "🫶", "👍", "👏", "🙌", "🙏", "💪", "🤝", "👌", "✌️", "🤞", "🫰", "🤟", "✨", "🌟", "⭐", "💫", "🔥", "💯", "🎉", "🎊", "🎁", "🏆", "🥇", "🚀", "🌈", "☀️", "🌸", "🌹", "🌺", "🌻", "🌷", "🍀", "🌿", "💎", "👑", "🕊️", "☮️"];
const N=j=>String(j||"").split("@")[0].split(":")[0].replace(/\D/g,"");
const owner=j=>OWN.includes(N(j));
function unwrap(m){let x=m?.message||{};for(const k of ["ephemeralMessage","viewOnceMessage","viewOnceMessageV2","viewOnceMessageV2Extension"])if(x[k]?.message)x=x[k].message;return x||{}}
function text(m){const x=unwrap(m);return x.conversation||x.extendedTextMessage?.text||x.imageMessage?.caption||x.videoMessage?.caption||x.documentMessage?.caption||""}
function parse(s){if(!s||!s.startsWith(PREFIX))return null;const a=s.slice(PREFIX.length).trim().split(/\s+/);return{command:(a.shift()||"").toLowerCase(),args:a}}
const menu="╭━━〔 *SAMAR-MD* 〕━━╮\\n┃ 👑 *The-RUDE-x Cyber Team*\\n╰━━━━━━━━━━━━━━━━╯\\n\\n*GENERAL*\\n• .menu\\n• .help\\n• .ping\\n• .ping2\\n• .alive\\n• .uptime\\n• .id\\n• .owner\\n• .info\\n• .settings\\n• .version\\n\\n*AUTO / STATUS*\\n• .autoread\\n• .autoreact\\n• .statusview\\n• .statuslike\\n• .autotyping\\n• .setdelay\\n• .setreact\\n\\n*POSITIVE*\\n• .emoji\\n• .emojis\\n• .love\\n• .smile\\n• .happy\\n• .fire\\n• .thanks\\n• .congrats\\n• .bless\\n• .goodmorning\\n• .goodnight\\n• .motivation\\n• .quote\\n• .welcome\\n\\n*GROUP*\\n• .goodbye\\n• .antilink\\n• .tagall\\n• .hidetag\\n• .admins\\n• .ginfo\\n• .groupid\\n• .members\\n• .promote\\n• .demote\\n• .kick\\n• .add\\n• .tiny\\n• .circle\\n\\n*TEXT / TOOLS*\\n• .gothic\\n• .reverse\\n• .upper\\n• .lower\\n• .count\\n• .calc\\n• .time\\n• .date\\n• .echo\\n• .say\\n• .addcmd\\n• .delcmd\\n• .cmds\\n\\n*BOT*\\n• .mycmds\\n• .link\\n• .channel\\n• .team\\n• .botname\\n• .support\\n• .rules\\n";
function calc(s){if(!/^[0-9+*/().%\-\s]+$/.test(s))return null;try{const n=Function('"use strict";return ('+s+')')();return Number.isFinite(n)?String(n):null}catch{return null}}
function send(sock,from,msg,t){return sock.sendMessage(from,{text:t},{quoted:msg})}
async function handle({sock,msg,user,save,groupMeta}){
 const from=msg.key.remoteJid,sender=msg.key.participant||from,p=parse(text(msg));if(!p)return false;const {command,args}=p,arg=args.join(" "),reply=t=>send(sock,from,msg,t);
 if(user.customCommands?.[command]){await reply(user.customCommands[command]);return true}
 if(["menu","help"].includes(command)){await reply(menu);return true}
 const simple={ping:"🏓 PONG! ❤️ SAMAR-MD online",ping2:"🏓 PONG 2! ⚡✨",uptime:"⏱️ "+Math.floor(process.uptime())+"s 🚀",id:"🆔 Chat: "+from+"\n👤 Sender: "+sender,owner:"👑 SAMAR-MD OWNER\n⚡ The-RUDE-x Cyber Team",version:"🚀 SAMAR-MD v5.0.0",team:"👑 The-RUDE-x Cyber Team",botname:"🤖 SAMAR-MD",channel:"📢 Official Channel\n"+(process.env.CHANNEL_LINK||"")};
 if(simple[command]){await reply(simple[command]);return true}
 if(command==="alive"){await reply("🟢 SAMAR-MD ALIVE\n👑 The-RUDE-x Cyber Team\n💖 Positive mode ON");return true}
 if(command==="info"){await reply("🤖 SAMAR-MD\n⚡ The-RUDE-x Cyber Team\n🟢 Multi-session\n💖 Positive reactions");return true}
 if(command==="settings"){await reply("⚙️ "+JSON.stringify(user.settings,null,2));return true}
 for(const k of ["autoread","autoreact","statusview","autotyping","welcome","goodbye","antilink"])if(command===k){if(!["on","off"].includes(args[0])){await reply("Use: ."+k+" on/off");return true}user.settings[k]=args[0]==="on";await save();await reply("✅ "+k+" "+(user.settings[k]?"ON 🟢":"OFF 🔴"));return true}
 if(command==="statuslike"){if(!["on","off"].includes(args[0])){await reply("Use: .statuslike on/off");return true}user.settings.statusview=args[0]==="on";user.settings.autoreact=args[0]==="on";await save();await reply("💚 STATUSLIKE "+args[0].toUpperCase()+"\n👀 Seen: "+(user.settings.statusview?"ON":"OFF")+"\n❤️ Reaction: "+(user.settings.autoreact?"ON":"OFF"));return true}
 if(command==="setdelay"){const n=Number(args[0]);if(!Number.isFinite(n)){await reply("Use: .setdelay 0-60");return true}user.settings.statusDelayMs=Math.max(0,Math.min(60,n))*1000;await save();await reply("⏱️ Delay: "+n+"s");return true}
 if(command==="setreact"){user.settings.fixedreact=!arg||arg.toLowerCase()==="random"?null:arg.slice(0,8);await save();await reply("❤️ Reaction: "+(user.settings.fixedreact||"RANDOM POSITIVE"));return true}
 const positive={"love": "❤️ 🩷 💖 💗 💕 💞 💓 💘 💝 😍 🥰 🫶", "smile": "😊 😄 😁 😆 😅 😂 🤣 🙂 🙃 😉 😌 😇 🥹", "happy": "🥳 🤩 😍 😁 😄 🎉 🎊 ✨ 🌟 💫", "fire": "🔥 ❤️‍🔥 💯 🚀 ⚡ 🌟", "thanks": "🙏 ❤️ 🫶 🤝 ✨ Thank you! Stay blessed. 💖", "congrats": "🎉🎊 Congratulations! 🥳🏆💖 Keep shining! ✨🌟", "bless": "🙏💖 May you always stay happy, successful and blessed. ✨🕊️", "goodmorning": "☀️🌸 Good Morning! 😊💖 Have a beautiful and successful day! ✨", "goodnight": "🌙✨ Good Night! 😴💖 Stay blessed and sleep well. 🫶", "motivation": "💪🔥 Believe in yourself. Keep moving forward. 🚀✨ You can do it! 🏆", "quote": "✨ Keep your heart positive, your mind focused, and your goals bigger than your fears. 💖🚀"};
 if(positive[command]){await reply(positive[command]);return true}
 if(command==="emoji"){await reply(E[Math.floor(Math.random()*E.length)]);return true}
 if(command==="emojis"){await reply("💖 Positive Emoji Pack ("+E.length+"+):\n"+E.join(" "));return true}
 if(["tagall","hidetag"].includes(command)){if(!from.endsWith("@g.us")){await reply("❌ Group only.");return true}const m=await groupMeta(from),ids=m.participants.map(x=>x.id);const body=command==="tagall"?(arg||"📢 Everyone ❤️")+"\n\n"+ids.map(x=>"@"+N(x)).join(" "):(arg||"📢 Attention everyone ❤️");await sock.sendMessage(from,{text:body,mentions:ids},{quoted:msg});return true}
 if(["admins","ginfo","groupid","members"].includes(command)){if(!from.endsWith("@g.us")){await reply("❌ Group only.");return true}const m=await groupMeta(from);if(command==="ginfo")await reply("👥 "+m.subject+"\n👤 Members: "+m.participants.length+"\n🆔 "+from);if(command==="groupid")await reply("🆔 "+from);if(command==="members")await reply("👥 Members: "+m.participants.length+" 👑");if(command==="admins"){const ids=m.participants.filter(x=>x.admin).map(x=>x.id);await sock.sendMessage(from,{text:"👑 ADMINS\n"+ids.map(x=>"@"+N(x)).join("\n"),mentions:ids},{quoted:msg})}return true}
 if(["promote","demote","kick"].includes(command)){if(!from.endsWith("@g.us")){await reply("❌ Group only.");return true}const ids=msg.message?.extendedTextMessage?.contextInfo?.mentionedJid||[];if(!ids.length){await reply("Mention a member: ."+command+" @user");return true}try{await sock.groupParticipantsUpdate(from,ids,command==="kick"?"remove":command);await reply("✅ "+command.toUpperCase()+" completed. 💖")}catch{await reply("❌ Action failed. Bot must be group admin.")}return true}
 if(command==="add"){if(!from.endsWith("@g.us")){await reply("❌ Group only.");return true}const n=(args[0]||"").replace(/\D/g,"");if(!n){await reply("Use: .add 923xxxxxxxxx");return true}try{await sock.groupParticipantsUpdate(from,[n+"@s.whatsapp.net"],"add");await reply("✅ Added 🎉")}catch{await reply("❌ Could not add that number.")}return true}
 const ops={tiny:s=>[...s].map(c=>"ᴀʙᴄᴅᴇꜰɢʜɪᴊᴋʟᴍɴᴏᴘǫʀꜱᴛᴜᴠᴡxʏᴢ"[c.toLowerCase().charCodeAt(0)-97]||c).join(""),circle:s=>[...s].map(c=>"ⓐⓑⓒⓓⓔⓕⓖⓗⓘⓙⓚⓛⓜⓝⓞⓟⓠⓡⓢⓣⓤⓥⓦⓧⓨⓩ"[c.toLowerCase().charCodeAt(0)-97]||c).join(""),gothic:s=>[...s].map(c=>"𝔞𝔟𝔠𝔡𝔢𝔣𝔤𝔥𝔦𝔧𝔨𝔩𝔪𝔫𝔬𝔭𝔮𝔯𝔰𝔱𝔲𝔳𝔴𝔵𝔶𝔷"[c.toLowerCase().charCodeAt(0)-97]||c).join(""),reverse:s=>[...s].reverse().join(""),upper:s=>s.toUpperCase(),lower:s=>s.toLowerCase()};
 if(ops[command]){await reply(ops[command](arg)||"Give some text.");return true}
 if(command==="count"){await reply("🔢 Characters: "+arg.length+"\nWords: "+(arg.trim()?arg.trim().split(/\s+/).length:0));return true}
 if(command==="calc"){const r=calc(arg);await reply(r===null?"❌ Invalid calculation.":"🧮 "+arg+" = *"+r+"*");return true}
 if(command==="time"){await reply("🕐 "+new Date().toLocaleTimeString());return true}if(command==="date"){await reply("📅 "+new Date().toLocaleDateString());return true}if(["echo","say"].includes(command)){await reply(arg||"Give some text.");return true}
 if(command==="support"){await reply("💖 "+(process.env.CHANNEL_LINK||"Official channel")+"\n👑 The-RUDE-x Cyber Team");return true}
 if(command==="rules"){await reply("📜 RESPECT ❤️\n🚫 No spam\n🤝 Help each other\n✨ Stay positive\n🙏 Respect admins");return true}
 if(["addcmd","delcmd"].includes(command)){if(!owner(sender)){await reply("❌ Owner only.");return true}if(command==="addcmd"){const n=(args.shift()||"").toLowerCase().replace(/[^a-z0-9_]/g,"");if(!n||!args.length){await reply("Use: .addcmd name reply");return true}user.customCommands[n]=args.join(" ");await save();await reply("✅ ."+n+" added 💖")}else{const n=(args[0]||"").toLowerCase();if(!user.customCommands[n]){await reply("❌ Not found.");return true}delete user.customCommands[n];await save();await reply("🗑️ Deleted ✅")}return true}
 if(["cmds","mycmds"].includes(command)){await reply("🧰 Custom:\n"+(Object.keys(user.customCommands).map(x=>"."+x).join("\n")||"None"));return true}
 return false;
}
module.exports={handle,getText:text,unwrap};
